---
- name: Install PIP basic dependencies
  pip:
    requirements: /var/www/note_kfet/requirements.txt
    virtualenv: /var/www/note_kfet/env
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv_site_packages: true
  become_user: www-data
