# Generated by Django 2.2.19 on 2021-03-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weiclub',
            name='year',
            field=models.PositiveIntegerField(default=2021, unique=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='weiregistration',
            name='information_json',
            field=models.TextField(default='{}', help_text='Information about the registration (buses for old members, survey for the new members), encoded in JSON', verbose_name='registration information'),
        ),
    ]
