# Generated by Django 2.2.19 on 2021-08-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wei', '0002_auto_20210313_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='size',
            field=models.IntegerField(default=50, verbose_name='seat count in the bus'),
        ),
    ]
