image: python:3.6

stages:
  - test
  - quality-assurance

before_script:
  - pip install tox

py36-django22:
  image: python:3.6
  stage: test
  script: tox -e py36-django22

py37-django22:
  image: python:3.7
  stage: test
  script: tox -e py37-django22

linters:
  image: python:3.6
  stage: quality-assurance
  script: tox -e linters

  # Be nice to new contributors, but please use `tox`
  allow_failure: true
