# Generated by Django 2.2.16 on 2020-09-04 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='roles',
            field=models.ManyToManyField(to='permission.Role', verbose_name='roles'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='club',
            name='parent_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='member.Club', verbose_name='parent club'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='member_prof_user_id_30c316_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user'], name='member_memb_user_id_945dbc_idx'),
        ),
    ]
