# Generated by Django 2.2.16 on 2020-09-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_replace_null_by_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ml_events_registration',
            field=models.CharField(blank=True, choices=[('', 'No'), ('fr', 'Yes (receive them in french)'), ('en', 'Yes (receive them in english)')], default='', max_length=2, verbose_name='Register on the mailing list to stay informed of the events of the campus (1 mail/week)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='section',
            field=models.CharField(blank=True, default='', help_text='e.g. "1A0", "9A♥", "SAPHIRE"', max_length=255, verbose_name='section'),
        ),
    ]
