---
- name: Add buster-backports to apt sources if needed
  apt_repository:
    repo: deb http://{{ mirror }}/debian buster-backports main
    state: present
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version | int == 10

- name: Install note_kfet APT dependencies
  apt:
    update_cache: true
    install_recommends: false
    name:
      # Common tools
      - gettext
      - git
      - ipython3

      # Front-end dependencies
      - fonts-font-awesome
      - libjs-bootstrap4

      # Python dependencies
      - python3-babel
      - python3-bs4
      - python3-django
      - python3-django-crispy-forms
      - python3-django-extensions
      - python3-django-filters
      - python3-django-oauth-toolkit
      - python3-django-polymorphic
      - python3-djangorestframework
      - python3-lockfile
      - python3-memcache
      - python3-phonenumbers
      - python3-pil
      - python3-pip
      - python3-psycopg2
      - python3-setuptools
      - python3-venv

      # LaTeX (PDF generation)
      - texlive-xetex

      # Cache server
      - memcached

      # WSGI server
      - uwsgi
      - uwsgi-plugin-python3
  register: pkg_result
  retries: 3
  until: pkg_result is succeeded
