---
- name: Install PostgreSQL APT packages
  apt:
    update_cache: true
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
  register: pkg_result
  retries: 3
  until: pkg_result is succeeded

- name: Create role note
  when: DB_PASSWORD|length > 0 # If the password is not defined, skip the installation
  postgresql_user:
    name: note
    password: "{{ DB_PASSWORD }}"
  become_user: postgres

- name: Create NK20 database
  when: DB_PASSWORD|length >0
  postgresql_db:
    name: note_db
    owner: note
  become_user: postgres
