# Generated by Django 2.2.3 on 2019-07-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteclub',
            old_name='user',
            new_name='club',
        ),
    ]
