# Generated by Django 2.2.16 on 2020-09-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_replace_null_by_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='inactivity_reason',
            field=models.CharField(blank=True, choices=[('manual', 'The user blocked his/her note manually, eg. when he/she left the school for holidays. It can be reactivated at any time.'), ('forced', "The note is blocked by the the BDE and can't be manually reactivated.")], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invalidity_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='invalidity reason'),
        ),
    ]
