# Generated by Django 2.2.19 on 2021-03-13 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_remove_null_tag_on_charfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alias', to='note.Note'),
        ),
    ]
