# Generated by Django 2.2.28 on 2022-08-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bde',
            field=models.CharField(choices=[('BDE', 'BDE'), ('BDA', 'BDA'), ('BDS', 'BDS')], default='BDE', max_length=32, verbose_name='BD?'),
        ),
    ]
