# Generated by Django 2.2.28 on 2022-07-31 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0004_auto_20211005_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SogeCredit',
        ),
    ]
