# Generated by Django 2.2.16 on 2020-09-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_replace_null_by_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='data',
            field=models.TextField(blank=True, default='', verbose_name='new data'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='previous',
            field=models.TextField(blank=True, default='', verbose_name='previous data'),
        ),
    ]
