#!/usr/bin/env ansible-playbook
---

- hosts: all
  vars_prompt:
    - name: DB_PASSWORD
      prompt: "Password of the database (leave it blank to skip database init)"
      private: yes
  vars:
    mirror: deb.debian.org
  roles:
    - 1-apt-basic
    - 2-nk20
    - 3-pip
    - 4-certbot
    - 5-nginx
    - 6-psql
    - 7-postinstall
