#!/usr/bin/env ansible-playbook
---

- hosts: bde-note.adh.crans.org
  vars_prompt:
    - name: DB_PASSWORD
      prompt: "Password of the database"
      private: yes
  vars:
    mirror: deb.debian.org
    note:
      server_name: bde-note.adh.crans.org
  roles:
    - 1-apt-basic
    - 2-nk20
    - 3-pip
    - 4-certbot
    - 5-nginx
    - 6-psql
    - 7-postinstall
