#!/usr/bin/env ansible-playbook
---

- hosts: server
  vars_prompt:
    - name: DB_PASSWORD
      prompt: "Password of the database (leave it blank if this is a reinstallation)"
      private: yes
  vars:
    mirror: deb.debian.org
  roles:
    - 1-apt-basic
    - 2-nk20
    - 3-pip
    - 4-certbot
    - 5-nginx
    - 6-psql
    - 7-postinstall
