#!/usr/bin/env ansible-playbook
---

- hosts: bde-nk20-beta.adh.crans.org
  vars_prompt:
    - name: DB_PASSWORD
      prompt: "Password of the database"
      private: yes
  roles:
    - 1-apt-basic
    - 2-nk20
    - 3-pip
    - 4-nginx
    - 5-certbot
    - 6-psql
    - 7-postinstall
