# Generated by Django 5.1 on 2024-08-13 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionMask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(unique=True, verbose_name='rank')),
                ('description', models.CharField(max_length=255, unique=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'permission mask',
                'verbose_name_plural': 'permission masks',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='query')),
                ('type', models.CharField(choices=[('add', 'add'), ('view', 'view'), ('change', 'change'), ('delete', 'delete')], max_length=15, verbose_name='type')),
                ('field', models.CharField(blank=True, max_length=255, verbose_name='field')),
                ('permanent', models.BooleanField(default=False, help_text='Tells if the permission should be granted even if the membership of the user is expired.', verbose_name='permanent')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='model')),
                ('mask', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='permission.permissionmask', verbose_name='mask')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'unique_together': {('model', 'query', 'type', 'field')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('for_club', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='member.club', verbose_name='for club')),
                ('permissions', models.ManyToManyField(to='permission.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'role permissions',
                'verbose_name_plural': 'role permissions',
            },
        ),
    ]
